# -*- coding: utf-8 -*-
"""
Created on Thu Dec  4 11:43:31 2025

@author: Martina Sperling
"""
import argparse
import pandas as pd
import numpy as np
import os
from scipy.stats import lognorm

# Fixed date and timezone
fixed_date = "2025-10-29"
timezone = "+02:00"

# Lognormal distribution parameters for weekdays (fitted to real booking data). Lognormal fits are
# common for positive, right-skewed data: Limpert, Stahel, Abbt (2001), BioScience 51(5), 341-352.
shape = 2.2237755705994577
loc = -3.1509873133758948
scale = 22589.216591253877

# Lead-time acceptance shaping. The raw fit above is real but has an
# unbounded continuous tail - sampled directly, it produces prior-day
# bookings (created before the fleet's own horizon_start) for over half
# of all requests, and occasional multi-month outliers no real service
# would show. Calibrated against real stage-1 XML extractions (both
# available fleets, checked independently) so the prior-day share stays
# under 1/3 while still allowing rare 1-2+ week advance bookings, capped
# at LEAD_TIME_MAX_S:
#   accept(x) = 1                                  x <= LEAD_TIME_X0_S
#   accept(x) = (LEAD_TIME_X0_S / x) ** LEAD_TIME_DECAY_K   x <= LEAD_TIME_MAX_S
#   accept(x) = 0                                  x >  LEAD_TIME_MAX_S
# Smooth, single rule - no separate carved-out window for "old" bookings.
LEAD_TIME_X0_S = 3600        # 1 hour
LEAD_TIME_DECAY_K = 0.4
LEAD_TIME_MAX_S = 60 * 86400  # 60 days

def lead_time_accept_prob(x):
    """Vectorized acceptance probability for a raw lognormal draw."""
    prob = np.ones_like(x)
    mid = (x > LEAD_TIME_X0_S) & (x <= LEAD_TIME_MAX_S)
    prob[mid] = (LEAD_TIME_X0_S / x[mid]) ** LEAD_TIME_DECAY_K
    prob[x > LEAD_TIME_MAX_S] = 0.0
    return prob

def draw_positive_lognorm(n):
    """Draw n lognormal samples, thinned by lead_time_accept_prob via rejection sampling."""
    out = np.full(n, np.nan)
    pending = np.arange(n)
    while len(pending) > 0:
        v = lognorm.rvs(s=shape, loc=loc, scale=scale, size=len(pending))
        valid = v > 0
        prob = np.zeros_like(v)
        prob[valid] = lead_time_accept_prob(v[valid])
        accept = valid & (np.random.random(len(pending)) < prob)
        out[pending[accept]] = v[accept]
        pending = pending[~accept]

    return out

def fix_24_hour_time(time_str):
    """Convert '24:MM:SS' to '00:MM:SS' and flag next day."""
    if time_str.startswith("24:"):
        mmss = time_str[3:]
        return "00:" + mmss, True
    else:
        return time_str, False
    
def combine_date_time_iso(dt, tz=timezone):
    """Convert pandas Timestamp to ISO 8601 string with timezone."""
    return dt.strftime("%Y-%m-%dT%H:%M:%S") + tz


# --- Main ---

def parse_args():
    parser = argparse.ArgumentParser(
        description="Add SimulatedTime to trip JSON."
    )
    parser.add_argument(
        "input_file",
        help="Input JSON generated by read_tudo_agents.py",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=None,
        help="Output JSON path. Defaults to <input_without_ext>_simulatedtime_weekdays.json",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=10,
        help="Random seed for the lead-time draws.",
    )
    return parser.parse_args()


def main(input_file, output_file, seed=10):
    np.random.seed(seed)

    # Read JSON without auto date parsing
    df = pd.read_json(input_file, convert_dates=False)

    # --- Fix '24:xx:xx' times for start_time and end_time ---
    start_next_day_flags = []
    fixed_start_times = []
    for t in df["start_time"]:
        new_t, next_day = fix_24_hour_time(t)
        fixed_start_times.append(new_t)
        start_next_day_flags.append(next_day)
    df["start_time"] = fixed_start_times

    end_next_day_flags = []
    fixed_end_times = []
    for t in df["end_time"]:
        new_t, next_day = fix_24_hour_time(t)
        fixed_end_times.append(new_t)
        end_next_day_flags.append(next_day)
    df["end_time"] = fixed_end_times

    # Combine fixed date with start_time and end_time
    df["start_time"] = pd.to_datetime(f"{fixed_date} " + df["start_time"])
    df["end_time"] = pd.to_datetime(f"{fixed_date} " + df["end_time"])

    # Add 1 day to start_time/end_time if it was originally 24:xx:xx
    df.loc[start_next_day_flags, "start_time"] += pd.Timedelta(days=1)
    df.loc[end_next_day_flags, "end_time"] += pd.Timedelta(days=1)

    # Draw x_seconds from lognormal distribution
    x_seconds = draw_positive_lognorm(len(df)).round().astype(int)

    # Calculate SimulatedTime
    df["SimulatedTime"] = df["start_time"] - pd.to_timedelta(x_seconds, unit="s")

    # Format start_time, end_time, SimulatedTime as ISO 8601
    df["start_time"] = df["start_time"].apply(combine_date_time_iso)
    df["end_time"] = df["end_time"].apply(combine_date_time_iso)
    df["SimulatedTime"] = df["SimulatedTime"].apply(combine_date_time_iso)

    # Save JSON
    if os.path.exists(output_file):
        print(f"Output file '{output_file}' already exists and will be overwritten.")
    df.to_json(output_file, orient="records", indent=4)

    # Stats
    print(f"Total entries: {len(df)}")
    print(f"Unique person_id: {df['person_id'].nunique()}")
    print(f"New file written to: {output_file}")


if __name__ == "__main__":
    args = parse_args()
    output_file = args.output or f"{os.path.splitext(args.input_file)[0]}_simulatedtime_weekdays.json"
    main(args.input_file, output_file, args.seed)
